name: Build

on:
  push:
    tags:
      - "*"
  # Allow manual trigger
  workflow_dispatch:

jobs:
  ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    with:
      build_target: prod
      image_name: "ghcr.io/${{ github.repository }}"
      build_args: |
        COMMIT_REF=${{ github.sha }}
