name: Build

on:
  release:
    types: [published]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  extract-vars:
    uses: hotosm/gh-workflows/.github/workflows/py_app_version.yml@main
    with:
      package_name: osm_rawdata

  backend-ci-build:
    uses: hotosm/gh-workflows/.github/workflows/image_build.yml@main
    needs: [extract-vars]
    with:
      build_target: prod
      image_tags: |
        "ghcr.io/hotosm/osm-rawdata:${{ needs.extract-vars.outputs.app_version }}"
        "ghcr.io/hotosm/osm-rawdata:latest"
      build_args: |
        PKG_VERSION=${{ needs.extract-vars.outputs.app_version }}
